### ISSUE TITLE
Wrong player starts first

### ISSUE THREAD

**Issue by raspingbard** [new3Rs/a_master_of_go#103]
When I paste the SGF game below into SmartGo or EasyGo, black is the first player to move.  When I paste it into MoG, white is the first player.  Not sure why?

(;FF[4]GM[1]SZ[19]CA[UTF-8]AP[EasyGo:1.9.3]GN[S002 test]DT[2019-12-12]AB[md][ne][od][oe][of][pd][pf][pi][qd][qi][pp]AW[le][me][nc][nd][nf][og][pg][qe][qf][qh][dp][dd]GC[EasyGo:(type=game)]
(;B[mc];W[nb];B[mb];W[pb];B[qb];W[rb];B[qa];W[rc]
(;B[rd];W[qc];B[ob];W[oc];B[pc];W[oa];B[ma];W[na];B[ra]
;W[ld]C[Right, sacrifice four stones to live in upper right.])
(;B[qc];W[rd];B[kc]C[Right, capture four stones to live. ]))
(;B[pp];W[dd];AW[dp]))

**Comment by y-ich** [comment]
@raspingbard san,

MoG determines the first player by the existence of AB property if there is no PL property.
You can specify the first player by Adding PL property.

If there are concrete specification to determine the first player in SGF specifications, I will modify to follow it but I have not found it  yet.

Regard.

**Comment by raspingbard** [comment]
I see the concrete specification for the PL property, but it doesn't look like either SmartGo or EasyGo use it (strange).  If there were no PL property, I would have MoG look for the first black or white move after setup.  But, you can decide.

Thanks.

**Comment by y-ich** [comment]
@raspingbard san,

Thank you for your understanding.
SGF is complete for game scoring, but it is not enough as game settings.

I will modify when I largely refactor the app.

**Comment by new3Rs** [comment]
added look a head of the color of the first move in the next version.

**Comment by raspingbard** [comment]
Your fix above works in v5.0.7.  Thank you!

**Comment by new3Rs** [comment]
Thank you for reporting the issue!
