### ISSUE TITLE
Probabilities and colors are swapped

### ISSUE THREAD

**Issue by raspingbard** [new3Rs/a_master_of_go#104]
The following 13x13 game is causing several problems in MoG v5.1:

(;FF[4]GM[1]SZ[13]CA[UTF-8]AP[EasyGo:1.9.3]GN[2020-04-22-01]PB[blackname]PW[whitename]DT[2020-04-22]AW[lb][lc][hb][ic][hc][gb][cd][dj][kj]AB[fb][fc][gc][hd][id][jd][kd][ld][md]PL[B])

Paste SGF for Study (black to play).

Problem #1 - Black win rate is 56%, but best move is 44%.

Problem #2 - Colors are swapped:
    a)  Tap on K12 (black stone is played)
    b)  Tap on K13 (white stone is played)
    c)  Tap on K13 to undo move.  Stone on K12 is now white.

**Comment by new3Rs** [comment]
@raspingbard san,

Thank you for reporting bugs!
I confirmed both.
They will be fixed in the next version.
