### ISSUE TITLE
Help with Katago weight conversion to mlmodel

### ISSUE THREAD

**Issue by zaratesta** [new3Rs/a_master_of_go#105]
Hi new3Rs san,

Thank you for your wonderful app! I was trying to convert Katago weight to mlmodel, using the following command:

`./make.sh 13 https://github.com/lightvector/KataGo/releases/download/v1.4.0/g170-b40c256x2-s3708042240-d967973220.bin.gz`

and received this error message:

> Traceback (most recent call last):
>   File "save_graph.py", line 19, in <module>
>     version, blocks, filters, weights = read_net(sys.argv[2])
>   File "/Users/Alexandre/a_master_of_go-master/LZ2mlmodel/net2net.py", line 46, in read_net
>     for e, line in enumerate(f):
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/codecs.py", line 321, in decode
>     (result, consumed) = self._buffer_decode(data, self.errors, final)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 103: invalid continuation byte
> make: *** [tmp/graph.pbtxt] Error 1

Previously, I was able to converte Leela weights to mlmodel without this error. 
Could you help me, please?

Thanks in advance and kind regards,

**Comment by new3Rs** [comment]
@zaratesta san,

Thank you for using the app!

The script on this repository is for Leela Zero's weights, not for KataGo's.

For KataGo's, I had worked so many patches on coremltools, which is an open source by Apple for weight conversion.
I am sorry for you that I will keep the patches private for a while.
Instead, I may release converted 40b weights.

Please keep in mind that KataGo author Wu san  recommends 20b weight "for weak to midrange hardware" such as iPhone/iPad.
