### ISSUE TITLE
mlmodel usage

### ISSUE THREAD

**Issue by ychoi** [new3Rs/a_master_of_go#107]
I am interested in using KataGo MLModel in my Swift project.
     I integrated KataGoG170e_b15c192_fp16.mlmodel (well Xcode did) and ran a quick test.
     What I did so far is; created a KataGo model, and populated input data with a single move (3-3 point) and fed into the model. The prediction output seems odd to me, though.
     Probably I misformulated the input data, or something else...
     
     Could someone ( perhaps @y-ich ) can shed some light on this, how to use KataGo's mlmodel in iOS project?
     Specifically I would like to know how to formulate the input parameters to KataGoG170e_b15c192_fp16Input(), and how to intrepret the output from the KataGoG170e_b15c192_fp16Output().
     An example would be helpful.

**Comment by y-ich** [comment]
@ychoi san,

Thank you for your interest of my project!

You know, this repository is for my commercial app.
The usage of KataGoG170e_b15c192_fp16.mlmodel is a heart of my app^^
So I cannot disclose it.

I recommend you to start converting KataGo's TensorFlow model to mlmodel by [coremltools](https://github.com/apple/coremltools).
You will understand CoreML's mechanisms under the hood well.

Good luck!

**Comment by ychoi** [comment]
@y-ich san,
Thank you for prompt response and your recommendation coremltools.
Good luck with your project. 
Cheers!
