### ISSUE TITLE
How to pass in study mode

### ISSUE THREAD

**Issue by fqx** [new3Rs/a_master_of_go#110]

**Comment by new3Rs** [comment]
fqx san,

There are no ways to pass in study mode.

**Comment by fqx** [comment]
why not?

**Comment by new3Rs** [comment]
If you have a feature request, you can write your use case.

**Comment by fqx** [comment]
The use case is:
I use a go camera app, capture the go board and generate sgf file, open the file in a_master_of_go, I need to analyze the winning rate and what is the next best move.
The study mode in a_master_of_go will always start with white in this case, that's why I need a pass, or to choose which side plays next.

**Comment by new3Rs** [comment]
@fqx san,

"The study mode in a_master_of_go will always start with white in this case"
It is not true.
It may be a bug of the SGF file or the app.
Could you send the SGF file?

-edit-
Oh, I see that the go camera app generates an SGF which always starts with white.
You can ask to modify it to the author of the go camera app.
