### ISSUE TITLE
iPad miniでの操作性の向上について

### ISSUE THREAD

**Issue by nadesico19** [new3Rs/a_master_of_go#111]
当方はiPad mini (A17Pro)でプレーして気が付いたことですが、指先での置き間違えがたまにありました。対局モードでハガシが効かない為、勝負所でミスると一気に敗れてしまいます。つきましては、ダブルチェックみたいな機能は付けられないでしょうか？

**Comment by new3Rs** [comment]
@nadesico19 様、

ご意見ありがとうございます！

対局モードの場合、最終着手の石(◯マークの付いている石)をタップすると、自分の手番まで局面が戻ります。
お試しください。

**Comment by nadesico19** [comment]
> @nadesico19 様、
> 
> ご意見ありがとうございます！
> 
> 対局モードの場合、最終着手の石(◯マークの付いている石)をタップすると、自分の手番まで局面が戻ります。 お試しください。

確認不足でおさわがせしました。ご教示ありがとうございます。素晴らしいアプリで愛用させていただきます!
