### ISSUE TITLE
size 9

### ISSUE THREAD

**Issue by y-ich** [new3Rs/a_master_of_go#23]
from mjgjvmk san

**Comment by y-ich** [comment]
コミが5目半のウェイトはあるが、囲碁クエ的には7目が望ましい。
どうやって入手するか。

**Comment by ChinChangYang** [comment]
I am interesting in 9x9 board.

The weight file can be found at [here](http://storage.sjeng.org/zero/9x9-20-128.txt.gz).
The leela zero engine can be modified to 9x9 board by the following change:

-- #define BOARD_SIZE 19
++ #define BOARD_SIZE 9

A live 9x9 board with leela zero engine can be run in [colab](https://colab.research.google.com/drive/1JjbCu__TIJUpl6Wv7lvAAEsb2WO-M-n9).

**Comment by y-ich** [comment]
@ChinChangYang san,
Thank you for your interest in my app!

I know the weight which you suggested.
It is for 6.5 of komi, That actually means 5.5 of komi in Chinese rule.
(In Chinese rule, 6.5 and 5.5 of komi are same in most case.)
I am waiting for a weight for 7 of komi, which includes draw.

Thank you!

**Comment by y-ich** [comment]
version 3 will support size 9.
