### ISSUE TITLE
Tapping on main menu adds moves on the underlying game, causing a crash

### ISSUE THREAD

**Issue by MarcelGruenauer** [new3Rs/a_master_of_go#25]
In the main menu, choose "Start Study". Add some moves. Tap the red "X" in the lower right corner and tap "OK" to go back to the main menu.

Then you can tap on the main menu, for example, on the text block below "Reference", and it will still add moves to the board underneath. It also produces the "click sound". This is a bug.

Then when you tap "Start Study" again, the app crashes.

**Comment by y-ich** [comment]
Oh! I have never notice it. I confirmed it.
I will investigate the issue.

Thank you for your cooperation!

**Comment by y-ich** [comment]
fixed in the next version(1.1.1)
