### ISSUE TITLE
When going from play mode into study mode, the win rate is completely flat.

### ISSUE THREAD

**Issue by y-ich** [new3Rs/a_master_of_go#4]
that is, I think it only updates the win rate when a move is made.

from Mr. Grünauer

**Comment by y-ich** [comment]
I can not reproduce it. I need to ask  Grünauer san.

**Comment by MarcelGruenauer** [comment]
Now that I've explored the app further, I cannot reproduce it either. It was my mistake.

**Comment by y-ich** [comment]
I see.
Thank you for your collaboration!
If you find simillar phenomenon again, please let me know it via either lifein19x19 or a new issue.
