### ISSUE TITLE
App crashed twice in Study mode far in the game (about move 280)

### ISSUE THREAD

**Issue by hvdkrogt** [new3Rs/a_master_of_go#59]
On Ipad Pro the app died twice far into a game in study mode, around move 280.
Settings wear 30 secs a move and 3 threads. Battery saving off.

**Comment by y-ich** [comment]
Thank you for reporting the issue and I am sorry for inconvenience.

I wiil check.
I think that you are using first or second generation of iPad Pro. Is that rigtht?

**Comment by y-ich** [comment]
Sorry, I closed the issue by mistake.

**Comment by hvdkrogt** [comment]
Hi, no it is the new iPad Pro 2018 with the Bionic A12X processor with 64gb.
After syncing with my MacBook, I could not find a crash report.

**Comment by hvdkrogt** [comment]
This the game record by the way. This was a game against Crazy Stone deep learning on my Iphone 7 plus set at 5 dan. Crazy Stone was playing white. A Master of Go was playing with 30 seconds a move. It was remarkable that both programs were thinking that they were winning. Crazy Stone calculated it was winning with 2.5 points while Master thought it was winning from the beginning.

Started Date: 2018-12-25 02:13:18
Type of the Game: vs. Computer
Board Size: 19x19
Computer Level: 5d
Your Move: Black
Komi: 7.5
Handicap: None
Move: 248
Status: Playing
Rules: Chinese Rules
Game Mode: Normal Game

(;FF[1]SZ[19]PB[Player]PW[COMLv5d]BS[0]WS[20]KM[7.5]HA[0]RU[Chinese]AP[CS Pro]VW[]
GN[CS Pro]GC[]DT[2018-12-25 02:13:18]
;B[dp]TL[1,0];W[pp]TL[5,0];B[pd]TL[35,0];W[dc]TL[5,0]
;B[ce]TL[41,0];W[dh]TL[5,0];B[nq]TL[96,0];W[lq]TL[9,0]
;B[no]TL[38,0];W[pn]TL[9,0];B[jq]TL[47,0];W[lo]TL[9,0]
;B[jo]TL[51,0];W[nn]TL[9,0];B[ed]TL[43,0];W[ec]TL[9,0]
;B[fd]TL[37,0];W[gc]TL[9,0];B[gd]TL[80,0];W[hc]TL[5,0]
;B[hd]TL[44,0];W[ic]TL[9,0];B[ck]TL[66,0];W[dj]TL[9,0]
;B[dk]TL[108,0];W[fj]TL[9,0];B[id]TL[38,0];W[ek]TL[9,0]
;B[ei]TL[48,0];W[ej]TL[9,0];B[jc]TL[36,0];W[jb]TL[9,0]
;B[kb]TL[59,0];W[kc]TL[9,0];B[jd]TL[43,0];W[ib]TL[9,0]
;B[lc]TL[35,0];W[qf]TL[9,0];B[dm]TL[38,0];W[cq]TL[9,0]
;B[dq]TL[36,0];W[cp]TL[6,0];B[cn]TL[38,0];W[dr]TL[9,0]
;B[er]TL[33,0];W[cr]TL[5,0];B[fq]TL[12,0];W[co]TL[9,0]
;B[do]TL[34,0];W[pi]TL[9,0];B[bo]TL[50,0];W[bp]TL[5,0]
;B[bn]TL[34,0];W[ar]TL[9,0];B[hj]TL[11,0];W[gh]TL[9,0]
;B[hh]TL[36,0];W[hg]TL[9,0];B[ih]TL[35,0];W[gg]TL[9,0]
;B[ig]TL[45,0];W[df]TL[9,0];B[qk]TL[59,0];W[pk]TL[9,0]
;B[pl]TL[37,0];W[ok]TL[9,0];B[cc]TL[38,0];W[cb]TL[9,0]
;B[bi]TL[38,0];W[cf]TL[9,0];B[dd]TL[36,0];W[bc]TL[9,0]
;B[cd]TL[7,0];W[kd]TL[9,0];B[mb]TL[38,0];W[ke]TL[9,0]
;B[bb]TL[41,0];W[db]TL[9,0];B[me]TL[38,0];W[lf]TL[9,0]
;B[jf]TL[38,0];W[mf]TL[9,0];B[ff]TL[36,0];W[eg]TL[9,0]
;B[ch]TL[38,0];W[gl]TL[9,0];B[il]TL[41,0];W[cj]TL[9,0]
;B[bj]TL[37,0];W[cg]TL[9,0];B[ef]TL[46,0];W[el]TL[9,0]
;B[of]TL[43,0];W[og]TL[9,0];B[pg]TL[36,0];W[pf]TL[5,0]
;B[ng]TL[35,0];W[nf]TL[9,0];B[oh]TL[36,0];W[oe]TL[5,0]
;B[od]TL[43,0];W[og]TL[9,0];B[qg]TL[38,0];W[of]TL[9,0]
;B[ph]TL[36,0];W[qi]TL[9,0];B[rg]TL[38,0];W[rf]TL[9,0]
;B[rd]TL[36,0];W[mh]TL[9,0];B[oi]TL[38,0];W[mj]TL[9,0]
;B[pj]TL[37,0];W[qj]TL[9,0];B[oj]TL[35,0];W[rk]TL[9,0]
;B[ql]TL[38,0];W[rl]TL[9,0];B[nk]TL[7,0];W[ol]TL[5,0]
;B[nj]TL[5,0];W[nd]TL[9,0];B[nc]TL[36,0];W[ka]TL[9,0]
;B[lb]TL[34,0];W[mk]TL[9,0];B[nl]TL[10,0];W[om]TL[5,0]
;B[mn]TL[8,0];W[mo]TL[9,0];B[nm]TL[34,0];W[on]TL[5,0]
;B[lm]TL[39,0];W[nh]TL[9,0];B[np]TL[6,0];W[km]TL[9,0]
;B[kl]TL[35,0];W[ln]TL[9,0];B[mm]TL[37,0];W[jm]TL[9,0]
;B[jl]TL[37,0];W[in]TL[9,0];B[kn]TL[37,0];W[io]TL[9,0]
;B[jp]TL[35,0];W[hm]TL[9,0];B[lp]TL[35,0];W[md]TL[9,0]
;B[pr]TL[36,0];W[qq]TL[9,0];B[qr]TL[37,0];W[en]TL[9,0]
;B[hp]TL[38,0];W[dn]TL[9,0];B[cm]TL[35,0];W[gp]TL[9,0]
;B[hq]TL[36,0];W[fp]TL[9,0];B[ho]TL[44,0];W[gn]TL[9,0]
;B[ba]TL[36,0];W[dl]TL[9,0];B[cl]TL[37,0];W[qc]TL[9,0]
;B[qd]TL[37,0];W[ob]TL[9,0];B[pb]TL[7,0];W[pc]TL[9,0]
;B[qb]TL[35,0];W[oc]TL[9,0];B[rc]TL[8,0];W[bh]TL[9,0]
;B[bl]TL[45,0];W[gq]TL[9,0];B[gr]TL[36,0];W[es]TL[9,0]
;B[eq]TL[42,0];W[jn]TL[9,0];B[ko]TL[36,0];W[jj]TL[9,0]
;B[rr]TL[38,0];W[hk]TL[9,0];B[ll]TL[72,0];W[kh]TL[9,0]
;B[bd]TL[35,0];W[rq]TL[9,0];B[sq]TL[41,0];W[sr]TL[9,0]
;B[ss]TL[36,0];W[sp]TL[9,0];B[sr]TL[35,0];W[fs]TL[9,0]
;B[fr]TL[36,0];W[hf]TL[9,0];B[if]TL[37,0];W[je]TL[9,0]
;B[ie]TL[68,0];W[oq]TL[9,0];B[or]TL[36,0];W[rn]TL[9,0]
;B[nb]TL[38,0];W[ci]TL[9,0];B[bf]TL[37,0];W[aj]TL[9,0]
;B[ak]TL[38,0];W[ah]TL[9,0];B[ai]TL[37,0];W[rh]TL[9,0]
;B[sg]TL[37,0];W[ip]TL[9,0];B[iq]TL[38,0];W[af]TL[9,0]
;B[ae]TL[36,0];W[pq]TL[9,0];B[ac]TL[39,0];W[fc]TL[9,0]
;B[gs]TL[37,0];W[ds]TL[9,0];B[kj]TL[36,0];W[kk]TL[9,0]
;B[lk]TL[40,0];W[lj]TL[9,0];B[jk]TL[38,0];W[ji]TL[9,0]
;B[si]TL[36,0];W[sj]TL[9,0];B[sh]TL[36,0];W[bg]TL[9,0]
;B[be]TL[131,0];W[gj]TL[9,0];B[ij]TL[38,0];W[ri]TL[9,0]
;B[sf]TL[37,0];W[nr]TL[9,0];B[mr]TL[40,0];W[re]TL[9,0]
;B[se]TL[36,0];W[hr]TL[9,0];B[ir]TL[37,0];W[hl]TL[9,0]
;B[em]TL[44,0];W[fm]TL[9,0];B[la]TL[36,0];W[ja]TL[9,0]
;B[ld]TL[35,0];W[le]TL[9,0];B[kg]TL[39,0];W[lg]TL[9,0]
)

**Comment by y-ich** [comment]
@hvdkrogt san,

The version 1.5.0 is now in review.
This version will fix several bugs which causes app crash.
I hope that this version will fix the issue.
Please wait for a while.
