### ISSUE TITLE
App description on APPSTORE need to be fixed

### ISSUE THREAD

**Issue by ryouiki** [new3Rs/a_master_of_go#70]
JP : これでもほとんどのアマチュアの方が敵わない強さと思いますが、ご購入を検討いただく際にご注意ください。

上記の文章が英語と韓国語の翻訳で本来の意向と反対で表現されています。
次のように修正するのが良いと思います。

EN (current) :  I think that most amateurs are stronger than this, but please be careful when considering purchasing.
EN (fix to this) :  I think this is strong enough to beat most amateurs, but please be careful when considering purchasing.

KR (current) : 대부분의 아마추어는 이것보다 강하다고 생각하지만 구매를 고려할 때 조심하십시오.
KR (fix to this) : 이 정도로도 대부분의 아마추어 분들보다 강할 것으로 생각하지만 구매를 고려할 때 유의해 주시길 바랍니다.

**Comment by y-ich** [comment]
ご指摘ありがとうございます！

**Comment by y-ich** [comment]
2.0.0で修正。
