### ISSUE TITLE
粘贴sgf有bug

### ISSUE THREAD

**Issue by y-ich** [new3Rs/a_master_of_go#72]
粘贴摆好棋子的sgf文件时无法分辨黑先还是白先，即使在没有提子、盘面棋子数相同的情况下也会变成白先下

from China App Store

**Comment by y-ich** [comment]
SGFを送っていただいた。
手順で構成される棋譜ではなくて、AB,AWで局面を構成するSGFだった。
現在は、ABが存在すると白先と判定している。(置き碁も両方星に置く古い棋譜も白先だから)

AB,AWによる局面図は未サポートと連絡したが、どうするものか。

**Comment by new3Rs** [comment]
supported by PL property.
