### ISSUE TITLE
a good news

### ISSUE THREAD

**Issue by l1t1** [new3Rs/a_master_of_go#75]
apple released new pad with A12 soc,
can you test the app on them

**Comment by y-ich** [comment]
🎉
I am glad to hear it.

On A12(iPhone XS/XR), ELFv1 runs about max. 150nps.
If Apple made A12 clock-up for new iPad (it radiates heat more effectively), it should improve.

**Comment by y-ich** [comment]
"A12 Bionic in New iPad Paired With 3GB RAM, Clocks in at Same Speed as Latest iPhones"
https://www.macrumors.com/2019/03/18/new-ipad-benchmark-3gb-ram-12-bionic/
