### ISSUE TITLE
I cannot understand the review in App Store China well.

### ISSUE THREAD

**Issue by y-ich** [new3Rs/a_master_of_go#81]
支持一下围棋老师app，这是一个很好的开始，为在iOS设备上研究围棋提供了一个很好的手段，希望作者能够持续更新。
接下去作为一个腾讯野狐围棋APP、安卓平台阿Q围棋APP使用者，谈一谈我觉得有所欠缺的地方。
1.无法手动暂停AI引擎。本人使用iPhone X，一直开启会造成严重发热问题。另外，在某些简化的局面下无需AI计算，在摆棋的时候我也许只关注某个局面下的攻防，因此无需一直开启AI计算浪费资源。
2.在AI变化图下无法前进和后退一步。本人棋力不高，希望分析变化图中每一步的逻辑，只能一次性消化10步乃至20步的变化图压力很大。
3.没有试下功能。学棋并不仅仅意味着学习AI的优点，还需要发现自己的缺点。
4.没有本地棋谱。如果围棋老师提供一个本地记谱的功能，对于经常性的回顾会方便许多。
5.没有棋盘坐标。坐标对于分享、讲棋仍是需要的。

另外，可以参考阿Q围棋、腾讯围棋的某些好做法。
1.阿Q围棋的鹰眼功能，分析棋谱中提高胜率和降低胜率最多的的前10手。
2.阿Q围棋的不同风格主题。本人比较喜欢Sabaki风格。
3.腾讯围棋的形势功能（点目）。简单好用，形象直接。

我认为，现在AI已经足够强大，普通爱好者终其一生也无法击败AI。因此，围棋的乐趣已经不仅仅在追求更强，而需要更多关注推广、对初学者友好。希望作者的围棋老师APP能多多往此方向发展，为围棋在iOS平台的普及做一些力所能及的事情。

**Comment by ChinChangYang** [comment]
支持一下围棋老师app，这是一个很好的开始，为在iOS设备上研究围棋提供了一个很好的手段，希望作者能够持续更新。

I would like to praise this app. This is a good start that provides a good way to study go on iOS devices. I hope the developer will keep updating this app.

**Comment by ChinChangYang** [comment]
接下去作为一个腾讯野狐围棋APP、安卓平台阿Q围棋APP使用者，谈一谈我觉得有所欠缺的地方。

Next, I am an app user of 腾讯野狐围棋APP and 安卓平台阿Q围棋APP, so I would like to talk about what feature I think this app is missing.

**Comment by ChinChangYang** [comment]
1.无法手动暂停AI引擎。本人使用iPhone X，一直开启会造成严重发热问题。另外，在某些简化的局面下无需AI计算，在摆棋的时候我也许只关注某个局面下的攻防，因此无需一直开启AI计算浪费资源。

1. Unable to pause the AI engine manually. I am using iPhone X. If I keep it running, it will become very hot, seriously. In addition, I do not need AI computing in some simplified situation of go board. In studying go, I probably want to focus on the variations of attacking and defending at local go board, so it is not necessary to enable AI computation to waste the resources.

**Comment by ChinChangYang** [comment]
2.在AI变化图下无法前进和后退一步。本人棋力不高，希望分析变化图中每一步的逻辑，只能一次性消化10步乃至20步的变化图压力很大。

2. In AI’s go variations, it is impossible to go forward or backward. My go rating is not very high, so I wish to fully understand the logic of every move in the go variations. It is difficult to me if I have to read 10 moves or even 20 moves immediately.

**Comment by ChinChangYang** [comment]
3.没有试下功能。学棋并不仅仅意味着学习AI的优点，还需要发现自己的缺点。

3. No trialing mode (a mode that allows user to place any stones in the middle of a go game). Learning go is not only learning from AI, but also from the human himself/herself.

**Comment by ChinChangYang** [comment]
4.没有本地棋谱。如果围棋老师提供一个本地记谱的功能，对于经常性的回顾会方便许多。

4. No local go game records. If this app can provide a new feature of local go game record, it will be very convenient to review the games usually.

**Comment by ChinChangYang** [comment]
5.没有棋盘坐标。坐标对于分享、讲棋仍是需要的。

5. No board coordination. The coordination is needed to sharing and teaching go.

**Comment by ChinChangYang** [comment]
另外，可以参考阿Q围棋、腾讯围棋的某些好做法。
1.阿Q围棋的鹰眼功能，分析棋谱中提高胜率和降低胜率最多的的前10手。
2.阿Q围棋的不同风格主题。本人比较喜欢Sabaki风格。
3.腾讯围棋的形势功能（点目）。简单好用，形象直接。

Besides, I suggest to see those good features in 阿Q围棋 and 腾讯围棋.
1. 阿Q围棋‘s eagle eye, which can analyze and show the top 10 moves that increase or decrease win-rate in a go game.
2. 阿Q围棋‘s various themes. Personally I like Sabaki’s theme.
3. 腾讯围棋‘s score evaluation. Simple and intuitive.

**Comment by ChinChangYang** [comment]
我认为，现在AI已经足够强大，普通爱好者终其一生也无法击败AI。因此，围棋的乐趣已经不仅仅在追求更强，而需要更多关注推广、对初学者友好。希望作者的围棋老师APP能多多往此方向发展，为围棋在iOS平台的普及做一些力所能及的事情。

I think that the recent AIs are too strong to be beaten by ordinary go players in their whole life. Therefore, the interest of go is not only becoming stronger, but also more following, sharing, and friendly to beginners. I hope this app can be developed toward such direction. Do what we can do to make go more popular on iOS devices.

**Comment by y-ich** [comment]
@ChinChangYang san,

Thank you so much for your kind cooperation!
These are so helpful for me.

Can I ask you one question?
What is the meaning of "local" in "local go board" and "local go game record"?

Than you again!

**Comment by ChinChangYang** [comment]
Local go board, in the context, means the go variations appear in a small area of the go board. Here, “local” means a small area of the go board.

Local go game record, in the context, means save/load go game in the app. Here, “local” means the record is in the app data.

**Comment by y-ich** [comment]
I see!
Now they really make sense for me.

Thank you so much for your help!
