### ISSUE TITLE
Cloud storage in China for downloadable weights

### ISSUE THREAD

**Issue by y-ich** [new3Rs/a_master_of_go#82]
Dropbox is not accessible from China and github sounds like slow from China.

I tried to make an account of Baidu Yun in Japan but do not succeed.
Baidu Yun now seems not to accept foreign phone numbers.

**Comment by l1t1** [comment]
files.fm is ok

**Comment by y-ich** [comment]
@l1t1 san,
Thank you for your information!

I tried files.fm and seems successful though I need to modify my app a little.
Thank you!

**Comment by y-ich** [comment]
files.fm uses a query string in URL for file names and it confuses the app about file name.

**Comment by y-ich** [comment]
fixed in 3.4.1.
