### ISSUE TITLE
minigo v17 weight is too slow.

### ISSUE THREAD

**Issue by y-ich** [new3Rs/a_master_of_go#83]
Less than 30 nps on A12X.
Should be faster than 40b.

**Comment by l1t1** [comment]
should be as fast as lz 20x256
try source https://github.com/leela-zero/leela-zero/files/3164663/leela-zero-mg-0.17-src.zip wrote by @wpstmxhs
in  https://github.com/leela-zero/leela-zero/issues/2380

**Comment by y-ich** [comment]
@l1t1 san,

Thank you for your information.
Yes, I know it via the issue.
Since I just convert the original pb to mlmodel with coremltools, I have no clues why it is slow.
I am asking it on coremltools repository.

**Comment by new3Rs** [comment]
Global poolings or reduce ops in Core ML model make evaluations slow down.
No good workarounds.

**Comment by new3Rs** [comment]
A14 processor solved this issue.
