### ISSUE TITLE
Problem with Study Mode in v3.9.0

### ISSUE THREAD

**Issue by raspingbard** [new3Rs/a_master_of_go#88]
The new v3.9.0 version introduced a bad problem with Study Mode: you can't click on any other moves except those in the game record.  There's no way to explore new variations in Study Mode.

**Comment by y-ich** [comment]
raspingbard san,

I am sorry for this inconvenience.
It has been solved in 3.9.1.
Please update the app.

Thank you.

**Comment by raspingbard** [comment]
The new version is working again.  Thank for the quick fix!
