### ISSUE TITLE
could you publish a benchmark on A13 chip

### ISSUE THREAD

**Issue by l1t1** [new3Rs/a_master_of_go#92]
thanks

**Comment by new3Rs** [comment]
@l1t1 san,

Thank you for your interest in the app!

A iPhone 11 Pro user told me the following results.

ELF OpenGo v1 - about 150 eps (evaluations per sec.)
Leela Zero #242 - about 70 eps

**Comment by l1t1** [comment]
It's hard to believe that A13 is slower than a12x

**Comment by y-ich** [comment]
In my estimation, A13 is only 6% faster than A12X which has more GPU cores.
It may be hard to see the difference in the view point of users.
And the condition is not same, iOS 12 vs. iOS 13.
There is possibility that iOS 13 may slow down Core ML.
