### ISSUE TITLE
App crashes more with iPadOS 13

### ISSUE THREAD

**Issue by raspingbard** [new3Rs/a_master_of_go#95]
I've notice more crashes with the latest iPadOS 13 for my iPad Pro 12.9".  I play mostly 13x13 games, so I don't know if the new iOS affects 19x19 games too.

Attached is one of the crash logs.  There were about 10 total.  _All of the logs_ point to one of the threads running CoreML (as I suspected).

[ChildOfZero-2019-09-24-213046.ips.log](https://github.com/new3Rs/a_master_of_go/files/3668804/ChildOfZero-2019-09-24-213046.ips.log)

**Comment by new3Rs** [comment]
Thank you!

I will check 13x13.
I may remember that you set batch size to higher value.
Setting to 1, which avoid to use Core ML's batch predictions, may fix this issue.

**Comment by hvdkrogt** [comment]
I have only played on 19x19 on my Iphone Pro Max 256Gb. Both in Pair Go mode and regular games with different weight files.
There are more crash files. I add the last two. If you need more, I can send off course.



[ChildOfZero-2019-09-29-234228.ips.log](https://github.com/new3Rs/a_master_of_go/files/3670212/ChildOfZero-2019-09-29-234228.ips.log)
[ChildOfZero-2019-09-29-225940.ips.log](https://github.com/new3Rs/a_master_of_go/files/3670213/ChildOfZero-2019-09-29-225940.ips.log)

**Comment by new3Rs** [comment]
@hvdkrogt san,
Thank you!

Your files also indicate that the cause is due to Core ML same as raspingbard san's.

As I am mainly checking Study mode, I will check Game mode, too.

**Comment by raspingbard** [comment]
@new3Rs san, After you told me that Batch Size doesn't do anything, I reset it back to 1.

**Comment by new3Rs** [comment]
The version 3.10.0 was released.

Several bugs were fixed, but it seems that they are not related with this issue.
I hope that compiling with new Xcode/Swift 5.1 is effective for this issue.

**Comment by raspingbard** [comment]
Good news, no crashes today with 3.10.0.  Nice fix!
