### ISSUE TITLE
some request for oz, ox weight

### ISSUE THREAD

**Issue by zliu1022** [new3Rs/a_master_of_go#96]
hi

it’s a very good software and i bought it at the first sight. 

May i submit some kindly request
Can you put OZ series weight ,it’s very good weight can play handicap game very good.

Also the OX24 weight is very very strong even than the leelazero 40b weight. can you also put it  on the app?

Thank you very much!

**Comment by new3Rs** [comment]
@zliu1022 san,

Thank you for purchasing the app and your information!

This repository is exactly for you.
You can convert any Leela Zero compatible weights to the one for “A Master of Go”.
Please see https://github.com/new3Rs/a_master_of_go/blob/master/LZ2mlmodel/README.md

**Comment by zliu1022** [comment]
Thanks.

Do you have plan to support color-plane dynamic komi algorithm in leeazero?
When I use OZ weight to play handicap game (>=4 stones), I find still need a handicap leelazero engine to support it.

I think the code to support color-plane will be easy and also will compatible with the existing engine you are using now, so the `komi xx` command will transfer the komi value to color plane.
And when use the OZ weight, just like OZ14.... The winrate will change very linear according the different handicap stones.
https://github.com/leela-zero/leela-zero/issues/1599

**Comment by new3Rs** [comment]
@zliu1022 san,

Thank you for your request!
I will consider about it.

**Comment by zliu1022** [comment]
I think katago now perfect replace leelazero.
I purchase katago inside go master.
Thanks

**Comment by new3Rs** [comment]
@zliu1022 san,

Thank you for unlocking KataGo!
I knew that your request would be solved by unlocking KataGo, but I hesitated to recommend paying extra money to you since you were a new user at that time.

I hope that you enjoy my app.

**Comment by zliu1022** [comment]
@new3Rs Hi,
Very unlucky, recently I find master of go can't be updated in China iOS App store.
Is it possible to transfer my purchase to global App store, I also have global account and can find "master of go" in Global iOS App store, but can't update anymore.
Anyway it depends on you. Any results can't change the fact that I love this app, so I wish can use it for a longer time ^_^

**Comment by y-ich** [comment]
@zliu1022 san,

I am sorry that the app miss you in China.

Apple has all responsibilities and decisions about app purchases.
You can talk with Apple, though I am afraid that it is hopeless since refunding expires within 90 days.

Thank you for your love to "围棋老师"!
