### ISSUE TITLE
More Minor Improvements

### ISSUE THREAD

**Issue by raspingbard** [new3Rs/a_master_of_go#97]
Hi Yuji-san,

Thanks for the recent updates to the weights.  I have a few more suggestions:

1.	As mentioned before, it would be nice to have a Pause button so I can think about moves without burning up my batteries.

2.	I want to use the arrow keys on my Smart Keyboard for iPad Pro to move forward and backward through games.

A small bug:

1.	Swiping with four fingers to switch apps adds an extra "ghost" move on the Go board.  This is kind of annoying.

Thank you!

**Comment by new3Rs** [comment]
@raspingbard san,

Thank you for your feature requests and bug report!

1. Setting "Max time per position(sec.)" finite time may help you temporarily.

I will consider these issues.

**Comment by new3Rs** [comment]
@raspingbard san,

I released version 4.0.0.

You can use hardware keyboard in this version.
 space=toggle suspend/resume engine
 cursor keys=play/back/forward/rewind
 "v"=toggle variation
 "s"=stop
 "l"=next chart
 "h"=previous chart
 "t"=toggle displaying dominating areas

And I fixed “ghost” move by task switch, too.

Thank you for your cooperations!

**Comment by raspingbard** [comment]
@Yuji-san,

This is a great upgrade!  If there was a Donate button, I would click it many times!

I have a few problems though:
1)  I'm not able to purchase KataGo.  I get an "invalid product ID" message (see screenshot).
2) If I stop the engine with "s" key, then type left or right arrow key, the app hangs.

Thanks

![Invalid product ID](https://user-images.githubusercontent.com/28121941/70732506-c657cf80-1cc5-11ea-8f7f-fcb94ba68b13.jpeg)

**Comment by new3Rs** [comment]
@raspingbard san,

I am sorry that unlocking KataGo is not available yet due to my mistake of procedure.
Please wait for a few days.

The second issue that you pointed out must be a bug.
I will check it.

Thank you!

**Comment by raspingbard** [comment]
@Yuji-san,

I was able to download v4.0.1 and now I can unlock KataGo.  This is a great addition to your app!  The new keyboard support is also wonderful.

I found another small bug: if you change the handicap stones to 5 and then the grid size to 9, the app crashes.

-Raspingbard

**Comment by new3Rs** [comment]
@raspingbard san,

I am glad to hear that you seem enjoy the new version.

Now the version 4.0.2 is available and it fixes the bug which you pointed out.

Thank you!
