### ISSUE TITLE
KataGo

### ISSUE THREAD

**Issue by raspingbard** [new3Rs/a_master_of_go#98]
I have a question on the new KataGo network: KataGo is supposed to be capable of playing well using high handicap stones (due to training on optimal score-values in addition to win-rates).  It is also supposed to allow custom grid sizes (e.g. 6 x 12), and large komi amounts (including reverse komi).

Do you expect that we will see these enhancements supported in the future?  (I don’t want to spoil any surprises for us :-)

Also, I noticed that KataGo doesn’t display node evaluations per second during game play, but does during game analysis.  Is this a limitation of the network?

**Comment by new3Rs** [comment]
@raspingbard san,

I will check high handicap games by KataGo.
About custom grid sizes, I think that I won't support them because boundary checks of layout may be harder than current.
(Even now, some people reported that go board protrudes screen at landscape, but I cannot reproduce it by simulators. It become hard for me to control Apple's Auto Layout technology.)

In game mode, KataGo displays only eps and does not display nps due to the difference of APIs.
It is not difficult to implement it but I thought that it is not necessary.

**Comment by raspingbard** [comment]
@Yuji-san,

That sounds good.  I think the best thing would be high handicap stones and high komi support.  The other things are not as important.

Is it possible to allow KataGo to be selected for 9x9 and 13x13 games too?

**Comment by new3Rs** [comment]
@raspingbard san,

If you edit your SGF file, you can try any handicap games and/or any komis.
Enjoy!

And the version 4.0.2 makes possible for you to play 9x9 and 13x13 games.

**Comment by raspingbard** [comment]
@Yuji-san,

I downloaded v4.0.2 and had some comments and questions:
1)  First, it's great the KataGo now runs on the Neural Engine and works on 9x9 and 13x13 grids.  This is really nice!
2)  I can paste an SGF game to review with high komi (positive or negative) and KataGo adjusts its win-rate according.  Nice again!
3)  When reviewing a game with KataGo, I now see additional indicators on the moves like "-5 +/- 24".  Can you tell me what this means?

And a few issues:
1) When I paste an SGF file with negative komi to play a game, I get a message like "Komi is -20, but 7.5 is adopted".  Can you allow this to work with KataGo?
2) I still have the hanging problem after pausing the engine and pressing an arrow key.  Can you allow the arrow keys restart the engine and play the next move?

Thanks.

**Comment by new3Rs** [comment]
@raspingbard san,

"-5 +/- 24" means that the move leads to a situation of average 5 points behind for the turn and its standard deviation is 24 points.

Thank you for reporting issues.
I will fix them at next version. (It will appear on next year)
